services:
  - type: web
    name: cinebuzz
    env: node
    buildCommand: npm run build:full
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health 